#!/bin/bash

# Generate a Caddyfile whose site addresses cover every hostname/IP of this
# machine, so the self-signed certificates Caddy issues with `tls internal`
# contain all of them as Subject Alternative Names (SANs). This lets other
# machines connect over HTTPS using any name/IP they know for this box.
#
# Two endpoints are published, each protected with HTTP basic auth (username
# "admin", password taken from the PASSWORD environment variable, falling back
# to .env if set):
#   - Obsidian (ignis)    on :3002 -> ignis:8080
#   - code-server         on :4000 -> code-server:8443
#
# Sources of hostnames:
#   - machine hostname and FQDN
#   - IPv4 addresses of real interfaces (skips loopback, docker, bridges...)
#   - names mapped in /etc/hosts (skips localhost aliases)
#
# Usage:
#   ./scripts/generateCaddyfile.sh                # write config-caddy/Caddyfile
#   ./scripts/generateCaddyfile.sh /path/to/file  # write to a specific file
#   ./scripts/generateCaddyfile.sh -              # print Caddyfile to stdout

set -euo pipefail

# Project root, regardless of where the script is invoked from.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Use the same credentials docker-compose gets from .env (if present).
if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

PASSWORD="${PASSWORD:-}"

# bcrypt-hash a password for Caddy's basic_auth. Tries the cheapest
# available option on this machine first.
hash_password() {
  local pass="$1"
  if command -v caddy >/dev/null 2>&1; then
    caddy hash-password --plaintext "$pass"
  elif command -v htpasswd >/dev/null 2>&1; then
    htpasswd -nbB admin "$pass" | cut -d: -f2
  elif python3 -c 'import bcrypt' >/dev/null 2>&1; then
    python3 -c 'import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())' "$pass"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm caddy:2-alpine caddy hash-password --plaintext "$pass"
  else
    echo "error: no way to hash the password (install caddy or htpasswd)" >&2
    exit 1
  fi
}

collect_hosts() {
  {
    hostname
    hostname -f
    ip -o -4 addr show \
      | awk '$2 !~ /^(lo|docker|br-|veth|virbr|tun|vpn|wg)/ { split($4, a, "/"); print a[1] }'
    awk '$1 !~ /^#/ && $1 != "127.0.0.1" && $1 != "::1" { for (i = 2; i <= NF; i++) print $i }' /etc/hosts
  } | grep -v '^localhost$' | sort -u | sed '/^$/d'
}

OUT="${1:-$ROOT/config-caddy/Caddyfile}"

addrs_for() {
  collect_hosts | sed "s/\$/:$1/" | paste -sd, - | sed 's/,/, /g'
}

emit() {
  local auth_block
  auth_block=''
  if [[ -n "$PASSWORD" ]]; then
    auth_block=$'\tbasic_auth {\n\t\tadmin '"$(hash_password "$PASSWORD")"$'\n\t}\n'
  else
    echo "warning: PASSWORD not set, generating without basic auth" >&2
  fi

  cat <<EOF
# Auto-generated by generateCaddyfile.sh at $(date '+%Y-%m-%d %H:%M:%S')
# Self-signed cert covers: $(collect_hosts | paste -sd', ' -)

{
	servers :3002 {
		listener_wrappers {
			http_redirect tls
		}
	}

	servers :4000 {
		listener_wrappers {
			http_redirect tls
		}
	}
}

localhost:3002, $(addrs_for 3002) {
	tls internal
${auth_block}	reverse_proxy ignis:8080
}

localhost:4000, $(addrs_for 4000) {
	tls internal
${auth_block}	reverse_proxy code-server:8443
}
EOF
}

if [[ "$OUT" == "-" ]]; then
  emit
else
  mkdir -p "$(dirname "$OUT")"
  emit > "$OUT"
  echo "Wrote $OUT with these addresses (all become cert SANs):" >&2
  collect_hosts | sed 's/^/  - /' >&2
fi
